//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basvuru
    {
        public int id { get; set; }
        public int kullanici_id { get; set; }
        public bool onaylandimi { get; set; }=false;
    }
}
