//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu1._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yurt_kayit_bilgileriEntities : DbContext
    {
        public yurt_kayit_bilgileriEntities()
            : base("name=yurt_kayit_bilgileriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<basvuru> basvuru { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<personel> personel { get; set; }
    }
}
